version: '3.7'

services:

  cheshire-cat-awesome-plugins-backend:
    build:
      context: .
    container_name: cheshire_cat_awesome_plugins_backend
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    restart: unless-stopped